#!/bin/sh

usage () {
    echo "usage: $0 {configure,build,install,uninstall,clean,distclean}"
}

case "$1" in
    "configure" ) echo "Done." ;;
    "build" ) ocamlbuild build ;;
    "install" ) ocamlbuild install ;;
    "uninstall" ) ocamlbuild uninstall ;;
    "clean" ) rm -fr _build ;;
    "distclean" ) rm -fr _build ;;
    "help" | "-help" | "--help" | "-h" ) usage ;;
    * )
        echo "Don't know what to do with '$1'"
        usage
        exit 2 ;;
esac

