(** Illumina specific features. *)
open Batteries_uni

(** Features specific to Illumina FASTQ files. Meant to be used in
    conjunction with the {!Biocaml.Fastq} module. *)
module Fastq : sig
  exception Error of string

  type sequence_id = {
    instrument : string;
    run_number : int;
    flowcell_id : string;
    lane : int;
    tile : int;
    x_pos : int;
    y_pos : int;
    read : int;
    is_filtered : bool;
    control_number : int;
    index : string
  }

  val sequence_id_of_string : string -> sequence_id
    (** Parse sequence ID in string format, as generated by
        {!Biocaml.Fastq}, according to the format followed by Illumina. *)

end
